name: Push - Single Build & Test (on push)

# workflow is for a branch push only and ignores main.
# push to main (which is also pull request merge) has a more elaborate workflow to run
# github repo is configured with branch protection on main.
on: 
  push:
    branches-ignore:
      - 'main'
      # any branch with a name ending in -no-action will not trigger this workflow.
      - '*-no-action'

  workflow_dispatch:
    inputs: 
      node:
        required: false
        description: 'A node version (e.g 10.16.0)'
        default: '18'

jobs:
  build-single-test:
    name: Build Single Test
    runs-on: ubuntu-latest # environment job will run in

    env:
      SW_APM_SERVICE_KEY: ${{ secrets.SW_APM_SERVICE_KEY }}
      SW_APM_COLLECTOR: ${{ secrets.SW_APM_COLLECTOR }}
      SW_TEST_PROD_SERVICE_KEY: ${{ secrets.SW_TEST_PROD_SERVICE_KEY }}

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v3

      - name: Setup Node ${{ github.event.inputs.node || '18' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ github.event.inputs.node || '18' }}
          cache: 'npm'

      - name: Show Environment Info
        run: |
          printenv
          node --version
          npm --version
          cat /etc/os-release

      - name: NPM Install dependencies
        run: npm ci

      # runs: node build.js for the current node version
      - name: Build from source
        run: npm run build

      - name: Run tests
        run: npm test
